-- ==========================================
-- SCRIPT DE CONFIGURACIÓN PARA SUPABASE
-- Ejecuta este script en el "SQL Editor" de tu proyecto de Supabase
-- ==========================================

-- 1. CREACIÓN DE LA TABLA DE CONVOCATORIAS (VACANTES)
CREATE TABLE IF NOT EXISTS convocatorias (
    id BIGINT PRIMARY KEY, -- Usamos BIGINT para admitir los timestamps Date.now() del JS original
    cargo TEXT NOT NULL,
    nivel TEXT NOT NULL,
    modalidad TEXT NOT NULL,
    vacantes INTEGER NOT NULL DEFAULT 1,
    cierre DATE NOT NULL,
    area TEXT,
    "desc" TEXT,
    estado TEXT NOT NULL DEFAULT 'Borrador',
    creada_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- 2. CREACIÓN DE LA TABLA DE POSTULACIONES
CREATE TABLE IF NOT EXISTS postulaciones (
    id BIGINT PRIMARY KEY, -- Usamos BIGINT para admitir los timestamps Date.now()
    nombre TEXT NOT NULL,
    documento TEXT NOT NULL,
    ciudad TEXT,
    telefono TEXT,
    correo TEXT NOT NULL,
    perfil TEXT,
    profesion TEXT,
    experiencia TEXT,
    area TEXT,
    certificado TEXT,
    ajustes TEXT,
    pdf TEXT,
    pdf_url TEXT,
    tiene_pdf BOOLEAN DEFAULT FALSE,
    convocatoria_id BIGINT REFERENCES convocatorias(id) ON DELETE SET NULL,
    convocatoria_nombre TEXT,
    estado TEXT NOT NULL DEFAULT 'Pendiente',
    history JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- 3. CREACIÓN DE LA TABLA DE USUARIOS (ADMINISTRADORES)
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario TEXT UNIQUE NOT NULL,
    nombre TEXT NOT NULL,
    password TEXT NOT NULL,
    rol TEXT NOT NULL DEFAULT 'Administrador',
    estado TEXT NOT NULL DEFAULT 'Activo',
    ultimo_acceso TEXT DEFAULT '—'
);

-- 4. INSERTAR USUARIO ADMINISTRADOR POR DEFECTO
-- Reemplaza 'admin123' por la contraseña que desees
INSERT INTO usuarios (usuario, nombre, password, rol, estado, ultimo_acceso)
VALUES ('admin', 'Administrador Principal', 'admin123', 'Administrador', 'Activo', '—')
ON CONFLICT (usuario) DO NOTHING;

-- 5. CREACIÓN AUTOMÁTICA DEL BUCKET DE ALMACENAMIENTO 'cv_files'
-- Nota: Hacemos que el bucket sea público para poder obtener URLs de descarga fácilmente
INSERT INTO storage.buckets (id, name, public)
VALUES ('cv_files', 'cv_files', true)
ON CONFLICT (id) DO NOTHING;

-- Habilitar políticas de seguridad para el bucket si es necesario
CREATE POLICY "Permitir subidas públicas" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'cv_files');

CREATE POLICY "Permitir lecturas públicas" ON storage.objects
    FOR SELECT USING (bucket_id = 'cv_files');

CREATE POLICY "Permitir eliminaciones públicas" ON storage.objects
    FOR DELETE USING (bucket_id = 'cv_files');

-- 6. HABILITAR ROW LEVEL SECURITY (RLS) EN LAS TABLAS (Opcional pero recomendado para seguridad)
-- Para simplificar el prototipo y permitir la conexión inicial, habilitaremos políticas de acceso público:

ALTER TABLE convocatorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE postulaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;

-- Políticas para convocatorias: Todos pueden leer (para ver vacantes), solo admins pueden modificar
CREATE POLICY "Acceso público de lectura a convocatorias" ON convocatorias
    FOR SELECT USING (true);

CREATE POLICY "Acceso total a administradores sobre convocatorias" ON convocatorias
    USING (true) WITH CHECK (true);

-- Políticas para postulaciones: Todos pueden insertar (postularse), todos pueden leer su propia postulación, admins control total
CREATE POLICY "Acceso público para insertar postulaciones" ON postulaciones
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Acceso total a postulaciones" ON postulaciones
    USING (true) WITH CHECK (true);

-- Políticas para usuarios: Permitir autenticación y gestión
CREATE POLICY "Acceso total a usuarios" ON usuarios
    USING (true) WITH CHECK (true);
